### ISSUE TITLE
[Bug]: After saving download is not working

### ISSUE THREAD

**Issue by casbizz** [saade/filament-autograph#1]
### What happened?

When i draw something and save as file  directly, everything works ok, but when you save it in the database and open the record again, it shows correctly, but when you save it as file there is no line anymore. In my case i used it for a signature, but the signature is not visible anymore

### How to reproduce the bug

- Add the signatur to a filament form
- load the form on your website and sign
- save the form
- open the form again
- save as jpg / png / svg
- open the saved file
- you see a empty image

![Screenshot 2023-08-24 101846](https://github.com/saade/filament-autograph/assets/40021129/202b8646-1199-4c8a-8a90-14a602cbfe3f)

### Package Version

3.0.0

### PHP Version

8.2.8

### Laravel Version

10.19.0

### Which operating systems does with happen with?

Windows

**Comment by saade** [comment]
thanks for reporting that, I will take a look at this over the weekend

**Comment by casbizz** [comment]
> thanks for reporting that, I will take a look at this over the weekend

I forget to tell you: "Very nice stuff you are making and sharing"

**Comment by noahlocke** [comment]
@casbizz how are you able to "save" the signature to your database? I just entered #3 as I'm unable to do so...

**Comment by casbizz** [comment]
Here some screenshots:
It saves in the database. The field is of type text in the database.

And in the filament resource i used the follwing:

SignaturePad::make('signature')
            ->label(__('Sign here'))
![Screenshot 2023-10-04 133619](https://github.com/saade/filament-autograph/assets/40021129/a4277c64-1c54-4e77-b8dd-2aae0dd366f8)

            ->dotSize(2.0)
            ->lineMinWidth(0.5)
            ->lineMaxWidth(2.5)
            ->throttle(16)
            ->minDistance(5)
            ->velocityFilterWeight(0.7)
            ->exportPenColor('#000-')
            ->exportBackgroundColor('#fff')
            ->undoable(false)
            ->clearable(false)
            ->downloadable(),


[cid:a555a0ce-7835-4e56-9d1b-e04c92de7b1d]

Met vriendelijk groet,
Caspar Bisschop
CasBizz Holding B.V.
***@***.******@***.***>
0654953817
________________________________

**Comment by casbizz** [comment]
> @casbizz how are you able to "save" the signature to your database? I just entered #3 as I'm unable to do so...

**Comment by abhi051002** [comment]
@casbizz hello please help me on this topic i was unable to store the signature to data please share me the code how to do it??
