### ISSUE TITLE
[Bug]: Method afterStateUpdated is not working

### ISSUE THREAD

**Issue by GuilhermeLegramante** [saade/filament-autograph#11]
### What happened?

I would like to return the signature data drawn. However, afterStateUpdated is not working. Is there some way that I can make this? 

### How to reproduce the bug

Method afterStateUpdated is not working.

### Package Version

^3.0

### PHP Version

8.2.0

### Laravel Version

10.0.0

### Which operating systems does with happen with?

Windows

**Comment by mgkimsal** [comment]
@GuilhermeLegramante  - you closed this, but no update on what was wrong.  Did it start working?  Did you work around this?

**Comment by GuilhermeLegramante** [comment]
> @GuilhermeLegramante - you closed this, but no update on what was wrong. Did it start working? Did you work around this?

Yes. If I remember correctly it was due to wrong library version or something like that.
