### ISSUE TITLE
[Bug]: Not working with Laravel 11

### ISSUE THREAD

**Issue by micraux** [saade/filament-autograph#18]
### What happened?

Hello,

The `composer require saade/filament-autograph` command fails with Laravel 11:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires saade/filament-autograph ^3.0 -> satisfiable by saade/filament-autograph[v3.0.0, v3.0.1, v3.0.2].
    - saade/filament-autograph[v3.0.0, ..., v3.0.2] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
As far I as I can tell, this is because the package requires only the version 10 for `illuminate/contracts`.

In the `composer.json` file, I suppose the `illuminate/contracts ^10.0` (line 26) sould be changed to `illuminate/contracts ^10.0|^11.0`.

I would love to make a PR to propose this change but I am not enough experienced with Git/GitHub to do it...

@saade, could you please have a look?

### How to reproduce the bug

Try to install on a fresh Laravel 11 / Filament 3 project.

### Package Version

3.0

### PHP Version

8.3

### Laravel Version

11.1

### Which operating systems does with happen with?

macOS

**Comment by micraux** [comment]
Hummm, I think I didn't point to the right direction as I can see the correct `"illuminate/contracts": "^10.0|^11.0",` in the `composer.json` file (line 26).

Any idea?

**Comment by micraux** [comment]
I can see the correct instruction in the `wip` commit (3 week ago).

Any plan to make a release which would include this change?

Thanks

**Comment by saade** [comment]
Its done

**Comment by micraux** [comment]
Great!
Thanks a lot!
