### ISSUE TITLE
[Bug]: Not writing to database

### ISSUE THREAD

**Issue by noahlocke** [saade/filament-autograph#3]
### What happened?

Maybe I'm missing something, but is the intention that the signature will persist in the database? Not seeing this behavior. If I draw a signature and save the form, nothing is written and the signature is lost if I refresh the page... 

### How to reproduce the bug

Install `filament-autograph`, add `SignaturePad::make('signature')` to resource form, draw signature & save resource. 

### Package Version

3.0

### PHP Version

8.2

### Laravel Version

10.0

**Comment by saade** [comment]
the base64 of the signature should being saved into your database

**Comment by noahlocke** [comment]
Got it, fixed on my end! Thank you for clarifying!

**Comment by abhi051002** [comment]
@noahlocke are you able to store the signature to your database if yes please tell  me how to do it??

**Comment by noahlocke** [comment]
@abhi051002 it was a stupid mistake on my end, forgot to add `'signature'` to the the `$fillable` array on the `User.php` model:

```php
    protected $fillable = [
        'name',
        'email',
        'password',
        'signature'
    ];
```
